### ISSUE TITLE
Problems with max_ttl on embedded systems

### ISSUE THREAD

**Issue by kingoflolz** [bluejekyll/trust-dns#528] opened 2018-07-12 11:17 UTC
Hi, I'm using trust-dns-resolver on some openwrt systems and found that version 0.9 crashes because it overflows time structs in `new_with_max_ttl`, as the time type defines seconds as an i32.

I've worked around this by making MAX_TTL lower (to one year), and from reading the RFC 2181 it seems that it is standard conforming behavior " Implementations are always free to place an upper bound on any TTL  received, and treat any larger values as if they were that upper bound".

However, I'm not familiar enough with the codebase to know what happens if trust-dns-resolver stays running for over a year, and if this will break any assumptions the rest of the code has in the codebase. If there are no problems with using a shorter max TTL, I suggest it be the default as the one we have right now makes it unusable on devices with a shorter time type

**Comment by azdlowry** [comment] 2018-07-31 11:44
Seem to be having this problem on 32bit Android as well. It's hard to narrow down the exact area of code that has the issue as backtraces don't work on Android.  But we get a panic with any of the resolvers:

thread 'service_location::test::run_trust_dns_example' panicked at 'overflow when adding duration to time', libcore/option.rs:960:5

**Comment by azdlowry** [comment] 2018-07-31 12:12
I've reduced MAX_TTL to 2^28-1 and it no longer panics. Though I don't think this is the best solution.

**Comment by bluejekyll** [comment] 2018-07-31 12:25
We could create a new TTL type that expresses maximum bounds with conversions from i32 as necessary, validating and storing a maximum based on platform.

**Comment by azdlowry** [comment] 2018-07-31 14:01
Only glanced through the code, so this might not be correct, but it seems the issue is with the use Instant type as this wraps a libc time_t structure, which is i32 on 32bit linux and i64 on 64bit linux. Should  trust-dns be using a different time structure that is consistent across platforms?

**Comment by bluejekyll** [comment] 2018-08-02 15:48
So one issue I have is access to a testing platform to verify a fix for this. The library relies on 'std::time::Duration' for all TTL and time evaluation, I don’t really want to change that, but we can add restrictions on top of that.

I’m fine with forcing these values to be safe for 32bit platforms. I don’t see any need for longer TTLs than that.

I propose a new TTL type that would enforce these limits and make it typesafe, but I’m open to other ideas.

**Comment by azdlowry** [comment] 2018-08-02 16:42
I'm happy to make the changes, and I can look into adding 32bit linux to CI as well.

My only concern with limiting the TTL is in picking a duration that is sensible. We can pick 19 years today but we'll be back here with the same problem in January 2019. If we say 10 years we'll be good till year 2028. If 10 years is good enough on 32 bit systems why is it not good enough on 64 bit systems as well? I think I don't understand the reason for the long TTL enough to be able to pick sensible ones.

I'll also have a look into replacing the Instant type with something that is consistent across platforms, then we don't need to change the TTL at all.

**Comment by bluejekyll** [comment] 2018-08-04 19:37
> If 10 years is good enough on 32 bit systems why is it not good enough on 64 bit systems as well? I think I don't understand the reason for the long TTL enough to be able to pick sensible ones.

If it sounded like I had a differing opinion on this, I apologize. I agree that it should be the same limit on 64bit and 32bit. TTL is really just a caching hint, too short is better than too long. I'm happy with anything over a week. The only reason the current values are there is that they seemed to be in accordance with the RFCs.

**Comment by bluejekyll** [comment] 2018-08-05 14:29
#542 and #543 are partial fixes for this issue. I would like us to come up with a type-safe response, but they will at least fix the current issue.

**Comment by bluejekyll** [comment] 2018-08-05 19:04
This `std::time` issue appears related: https://github.com/rust-lang/rust/issues/48980

**Comment by bluejekyll** [comment] 2018-08-05 19:37
I'm going to close this, we can reopen if we want to harden the TTL max with a type, but I think we might want to get saturating add into the std::time impls.

**Closed** 2018-08-05 19:37 UTC
Labels: bug, crate:resolver

**Comment by azdlowry** [comment] 2018-08-06 10:50
No apologies needed, I didn't want to dive into any changes without understanding all the details first. Saturating add does seem to be the best solution. Thanks.
