### ISSUE TITLE
tcp connection shutting down: io error

### ISSUE THREAD

**Issue by zonyitoo** [bluejekyll/trust-dns#560] opened 2018-09-23 11:58 UTC
```
Sep 23 19:55:04 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:06 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:06 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:06 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:06 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:06 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:06 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:06 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:06 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:07 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:07 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:12 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:12 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:12 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:12 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:22 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:22 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:57 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
Sep 23 19:55:57 VM-65-106-debian ssserver-rust[3076]: [ERROR] error, tcp connection shutting down: io error
```

I was using `cloudflare_tls` and the resolver kept showing these error logs. Are they expected? If so, can you lower the log level of this log?

**Comment by bluejekyll** [comment] 2018-09-23 15:02
Thanks for the report, I have noticed this, and I think this is a duplicate of #546

This may also be the related to #532

I'll be looking into these issues, soon. I think it does represent a real issue, and lowering the logging for it would probably mask a real bug that we should look into.

**Closed** 2018-10-05 17:07 UTC
